fio: Autospec creation for update from version 3.33 to version 3.34
Alberto Faria (10):
      Add a libblkio engine
      Add engine flag FIO_SKIPPABLE_IOMEM_ALLOC
      engines/libblkio: Allow setting option mem/iomem
      engines/libblkio: Add support for poll queues
      engines/libblkio: Add option libblkio_vectored
      engines/libblkio: Add option libblkio_write_zeroes_on_trim
      engines/libblkio: Add option libblkio_wait_mode
      engines/libblkio: Add option libblkio_force_enable_completion_eventfd
      engines/libblkio: Add options for some driver-specific properties
      engines/libblkio: Share a single blkio instance among threads in same process

Alexander Patrakov (1):
      fix fiologparser.py to work with new logging format

Ankit Kumar (9):
      engines:io_uring: fix clat calculation for sqthread poll
      doc: update about sqthread_poll
      doc: update about size
      engines/xnvme: fixes for xnvme ioengine
      engines/xnvme: user space vfio based backend
      engines/xnvme: add subnqn to fio-options
      engines/xnvme: add support for picking mem backend
      doc: clarify the usage of rw_sequencer
      backend: fix runtime when used with thinktime

Bart Van Assche (8):
      Windows: Fix the build
      Android: Enable zoned block device support
      configure: Fix clock_gettime() detection
      configure: Fix the struct nvme_uring_cmd detection
      os/os.h: Improve cpus_configured()
      io_u: Add a debug message in fill_io_u()
      zbd: Report the zone capacity
      zbd: Make an error message more detailed

Cuelive (1):
      blktrace: fix compilation error on the uos system

Horshack (11):
      Add -replay_skip support for fio-generated I/O logs
      Improve IOPs 50% by avoiding clock sampling when rate options not used
      SIGSEGV / Exit 139 when write_iolog used with io_submit_mode=offload
      Suppress sync engine QD > 1 warning if io_submit_mode is offload
      Read stats for backlog verifies not reported for time-expired workloads
      ioengines.c:346: td_io_queue: Assertion `res == 0' failed
      Bad header rand_seed with time_based or loops with randrepeat=0 verify
      Fix "verify bad_hdr rand_seed" for requeued I/Os
      Clarify documentation for runtime parameter
      Fix --bandwidth-log segmentation fault when numjobs even multiple of 8
      Refactor for_each_td() to catch inappropriate td ptr reuse

Jens Axboe (8):
      t/io_uring: adjust IORING_REGISTER_MAP_BUFFERS value
      Makefile: add -Wno-stringop-truncation for y.tab.o
      Enable crc32c accelleration for arm64 on OSX
      engines/libzbc: set FIO_RO_NEEDS_RW_OPEN engine flag
      Get rid of O_ATOMIC
      fdp: cleanup init
      Revert "ioengines.c:346: td_io_queue: Assertion `res == 0' failed"
      Fio 3.34

Keith Busch (1):
      fio: add fdp support for io_uring_cmd nvme engine

Logan Gunthorpe (6):
      cconv: Support pattern buffers of arbitrary size
      lib/pattern: Support NULL output buffer in parse_and_fill_pattern()
      lib/pattern: Support short repeated read calls when loading from file
      options: Support arbitrarily long pattern buffers
      lib/pattern: Support binary pattern buffers on windows
      test: add large pattern test

Richard W.M. Jones (1):
      examples: Small updates to nbd.fio

Shin'ichiro Kawasaki (28):
      oslib: blkzoned: add blkzoned_finish_zone() helper function
      engines/libzbc: add libzbc_finish_zone() helper function
      zbd: add zbd_zone_remainder() helper function
      zbd: finish zones with remainder smaller than minimum write block size
      zbd: allow block size not divisor of zone size
      zbd, verify: verify before zone reset for zone_reset_threshold/frequency
      zbd: fix zone reset condition for verify
      zbd: prevent experimental verify with zonemode=zbd
      t/zbd: fix test case #33 for block size unaligned to zone size
      t/zbd: modify test case #34 for block size unaligned to zone size
      t/zbd: add test case to check zone_reset_threshold/frequency with verify
      t/zbd: remove experimental_verify option from test case #54
      t/zbd: add test case to check experimental_verify option
      backend: respect return value of init_io_u_buffers
      man: fix troff warning
      HOWTO/man: improve descriptions of max open zones options
      example: add a zoned block device write example with GC by zone resets
      example: add a zoned block device write example with GC by trim workload
      zbd: refer file->last_start[] instead of sectors with data accounting
      zbd: remove CHECK_SWD feature
      zbd: rename the accounting 'sectors with data' to 'valid data bytes'
      doc: fix unit of zone_reset_threshold and relation to other option
      zbd: account valid data bytes only for zone_reset_threshold option
      zbd: check write ranges for zone_reset_threshold option
      zbd: initialize valid data bytes accounting at file setup
      t/zbd: add test cases for zone_reset_threshold option
      t/zbd: rename logical_block_size to min_seq_write_size
      t/zbd: fix minimum write size to sequential write required zones

Sven Hoexter (2):
      Spelling: Fix allows to -> allows one to in man 1 fio
      Use correct backslash escape in man 1 fio

Vincent Fu (24):
      docs: synchronize fio.1 and HOWTO changes
      docs: description for experimental_verify
      tools/fiograph: update config file
      examples: add missing fiograph diagrams
      t/run-fio-tests: relax acceptance criteria for t0008
      examples: add missing fiograph diagram for sg_write_same_ndob.fio
      tools/fiograph: add link to file formats
      tools/fiograph: improve default output file name
      tools/fiograph: improve default config file search
      examples: remove test.png
      tools/fiograph: accommodate job files not ending in .fio
      lib/pattern: Fix seg fault when calculating pattern length
      test: add test for lib/pattern segfault issue
      lib/pattern: fix formatting
      fio: add FIO_RO_NEEDS_RW_OPEN ioengine flag
      Revert "engines/libzbc: set FIO_RO_NEEDS_RW_OPEN engine flag"
      engines/libzbc: for read workloads always open devices with O_RDONLY flag
      ioengines: clarify FIO_RO_NEEDS_RW_OPEN flag
      examples: update nbd.fio fiograph diagram
      iolog: handle trim commands when reading iologs
      filesetup: don't skip flags for trim workloads
      configure: restore dev-dax and libpmem
      fdp: change the order of includes to fix Windows build error
      examples: add fiograph diagram for uring-cmd-fdp.fio

chienfuchen32 (1):
      update documentation typo

osalyk (1):
      pmemblk: remove pmemblk engine